# -*- coding: utf-8 -*-
"""major_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZlzSDI6940CTkInxu6qKOMpUHzljt56
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/seasonal_agriculture_performance_dataset.csv")
data.head()

data.tail()

data.describe()

data.info()

data.isnull().sum()

print(data.Crop.value_counts())

plt.figure(figsize=(10,6))
sns.barplot(x=data.Crop.value_counts().index, y=data.Crop.value_counts().values)
plt.title('Distribution of Crops')
plt.xlabel('Crop.Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt. show()

plt.figure(figsize=(10, 6))
sns. boxplot(x='Season', y='Production_Tonnes', data=data)
plt.title('Production (Tonnes) Across Different Seasons')
plt.xlabel('Season')
plt.ylabel('Production (Tonnes)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 7))
sns.barplot(x='Crop', y='Production_Tonnes', hue='Season', data=data, estimator=sum, ci=None)
plt.title('Total Production (Tonnes) by Crop and Season')
plt.xlabel('Crop Type')
plt.ylabel('Total Production (Tonnes)')
plt.xticks(rotation=45)
plt.legend(title='Season', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt. show()

g = sns.FacetGrid(data, col="Season", row="Crop", margin_titles=True, height=3, aspect=1.5)
g.map_dataframe(sns.scatterplot, x="Rainfall_mm", y="Production_Tonnes", size="Avg_Temperature_C", alpha=0.6, hue="Avg_Temperature_C", palette="coolwarm")
g.add_legend(title="Avg Temperature C")
g.set_axis_labels("Rainfall (mm)", "Production (Tonnes)")
g.fig. subplots_adjust(top=0.9)
g.fig. suptitle('Crop Production vs. Rainfall and Temperature across Seasons')
plt. show()

# Calculate mean values for Profit and Rainfall
season_crop_stats = data.groupby(['Season', 'Crop']).agg({
'Profit_INR': 'mean',
'Rainfall_mm': 'mean',
'Farm_ID': 'count'
}).reset_index().rename(columns={'Farm_ID': 'Frequency'})

fig, axes = plt.subplots(3, 1, figsize=(15, 18))

# Plot 1: Average Profit
sns.barplot(ax=axes[0], x='Crop', y='Profit_INR', hue='Season', data=season_crop_stats)
axes[0].set_title('Average Profit (INR) by Crop and Season')
axes[0].set_ylabel('Avg Profit')

# Plot 2: Average Rainfall
sns.barplot(ax=axes[1], x='Crop', y='Rainfall_mm', hue='Season', data=season_crop_stats)
axes[1].set_title('Average Rainfall (mm) by Crop and Season')
axes[1].set_ylabel('Avg Rainfall')

# Plot 3: Frequency (Count of records)
sns.barplot(ax=axes[2], x='Crop', y='Frequency', hue='Season', data=season_crop_stats)
axes[2].set_title('Frequency of Observations by Crop and Season')
axes[2].set_ylabel('Count')

plt.tight_layout()
plt. show()